server:
  port: ${PORT:9090}
  host: cyberdone.store
  protocol: http
  tomcat:
    max-http-form-post-size: 10MB
    max-swallow-size: 10MB
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://192.168.1.100:8761/eureka/
  instance:
    hostname: cyberdone.store
spring:
  application:
    name: cyber-done-cloud-gateway
    version: @version@
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
security:
  jwt-secret: ${JWT_SECRET}