server:
  port: ${PORT:9090}
  host: cyberdone.store
  protocol: http
eureka:
  instance:
    hostname: 192.168.1.100
spring:
  application:
    name: cyber-done-cloud-gateway
    version: @version@
security:
  jwt-secret: ${JWT_SECRET}